version: 2
updates: 
  # Enable version updates for nuget 
  - package-ecosystem: "nuget"
    # Look for NuGet dependency info from the `src` directory
    directory: "/src/" 
    # Check the nuget registry for updates every day (weekdays) schedule: 
    schedule:
      interval: "daily"